# Generated by Django 3.0.5 on 2020-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_auto_20200426_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_mark',
            field=models.CharField(default='unread', max_length=50, verbose_name='IsRead'),
        ),
    ]
